version: '2'

services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - sites:/var/www/html/sites
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  sites:
  modules:
  profiles:
  themes:
